demo/urls.py
from django.urls import path

from .views import BasinhoppingView, HeatMapView, SlsqpView, TaguchiView

app_name = 'demo'
urlpatterns = [
    path('optimization/basinhopping', BasinhoppingView.as_view(), name='basinhopping'),
    path('optimization/slsqp', SlsqpView.as_view(), name='slsqp'),
    path('optimization/taguchi', TaguchiView.as_view(), name='taguchi'),
    path('heat-map/', HeatMapView.as_view(), name='heat-map'),
    # path('optimization/', OptimizationView.as_view()),
    # path('fspl/', FSPLView.as_view())
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from rest_framework.authtoken import views

from base_station.views import (
     BasinhoppingView, HeatMapView, SlsqpView,
     TaguchiView, OptimizationView)
from map.views import index
from .api import router


urlpatterns = [
    # Base URLs
    path('admin/', admin.site.urls),
    path('api/', include((router.urls, 'django_project'), namespace='api')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', views.obtain_auth_token),
    path('login/', auth_views.login, {'template_name': 'admin/login.html'}, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('oauth2/', include('rest_framework_social_oauth2.urls')),

    # Demo URLs
    path('optimization/basinhopping', BasinhoppingView.as_view(), name='basinhopping'),
    path('optimization/slsqp', SlsqpView.as_view(), name='slsqp'),
    path('optimization/taguchi', TaguchiView.as_view(), name='taguchi'),
    #path('heat-map/', HeatMapView.as_view(), name='heat-map'),
    #path('optimization/', OptimizationView.as_view()),

    # Index URL
    #path('', index, name='index'),
]

optimization/models.py
from base_station.models import BaseStation


class OptimizedBaseStation(BaseStation):
    pass

demo/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
import logging

from base_station.models import IdentifiedBaseStation
from optimization.find_best_locations import OptimizeLocation
from optimization.numerical_methods import Basinhopping, SLSQP, Taguchi
from optimization.propagation_models import (
    AreaOptimization, FreeSpacePathLossOptimization)

from .use_cases.heat_map import HeatMap

logger = logging.getLogger(__name__)


class OptimizationView(TemplateView):
    template_name = 'demo/optimization.html'


class ExampleView(TemplateView):
    template_name = 'demo/example.html'

    @staticmethod
    def get_bounds_from_parameters(request):
        min_lat = float(request.GET['min_lat'])
        max_lat = float(request.GET['max_lat'])
        min_long = float(request.GET['min_long'])
        max_long = float(request.GET['max_long'])

        return ((min_lat, max_lat), (min_long, max_long))


class BasinhoppingView(ExampleView):

    def get(self, request, *args, **kwargs):
        bounds = ExampleView.get_bounds_from_parameters(request)
        NUMBER_OF_NEW_BSS = 5
        bounds = bounds * NUMBER_OF_NEW_BSS

        location = [bounds[0][0] + (bounds[0][1] - bounds[0][0])/2,
                    bounds[1][0] + (bounds[1][1] - bounds[1][0])/2]
        bss = IdentifiedBaseStation.get_base_stations_inside_bounds(
            bounds[0][0], bounds[1][0], bounds[0][1], bounds[1][1])\
            .filter(radio='GSM')
        
        optimize = OptimizeLocation(bss, bounds, Basinhopping(), AreaOptimization().objective)
        solution = optimize.find_best_locations()
        solution = [list(s) for s in solution]
        bs_coordinates = list(map(lambda bs: [bs.point.x, bs.point.y], bss))
        context = {
            'location': location,
            'base_stations': bs_coordinates,
            'suggestions': solution}
        return render(request, self.template_name, context)


class SlsqpView(ExampleView):

    def get(self, request, *args, **kwargs):
        bounds = ExampleView.get_bounds_from_parameters(request)
        NUMBER_OF_NEW_BSS = 2
        bounds = bounds * NUMBER_OF_NEW_BSS

        location = [bounds[0][0] + (bounds[0][1] - bounds[0][0])/2,
                    bounds[1][0] + (bounds[1][1] - bounds[1][0])/2]
        bss = IdentifiedBaseStation.get_base_stations_inside_bounds(
            bounds[0][0], bounds[1][0], bounds[0][1], bounds[1][1])\
            .filter(radio='GSM')

        optimize = OptimizeLocation(bss, bounds, SLSQP(), AreaOptimization().objective)
        solution = optimize.find_best_locations()
        solution = [list(s) for s in solution]
        bs_coordinates = list(map(lambda bs: [bs.point.x, bs.point.y], bss))
        context = {
            'location': location,
            'base_stations': bs_coordinates,
            'suggestions': solution}
        return render(request, self.template_name, context)


class TaguchiView(ExampleView):

    def get(self, request, *args, **kwargs):
        bounds = ExampleView.get_bounds_from_parameters(request)
        NUMBER_OF_NEW_BSS = 2
        bounds = bounds * NUMBER_OF_NEW_BSS

        location = [bounds[0][0] + (bounds[0][1] - bounds[0][0])/2,
                    bounds[1][0] + (bounds[1][1] - bounds[1][0])/2]
        bss = IdentifiedBaseStation.get_base_stations_inside_bounds(
            bounds[0][0], bounds[1][0], bounds[0][1], bounds[1][1])\
            .filter(radio='GSM')

        optimize = OptimizeLocation(bss, bounds, Taguchi(), AreaOptimization().objective)
        solution = optimize.find_best_locations()
        solution = [list(s) for s in solution]
        bs_coordinates = list(map(lambda bs: [bs.point.x, bs.point.y], bss))
        context = {
            'location': location,
            'base_stations': bs_coordinates,
            'suggestions': solution}
        print(AreaOptimization().objective(bss, solution))
        return render(request, self.template_name, context)


class HeatMapView(TemplateView):
    template_name = 'demo/heat-map.html'

    def get(self, request, *args, **kwargs):
        location = [-46.7302, -23.5572]
        bounds = ExampleView.get_bounds_from_parameters(request)
        bss = IdentifiedBaseStation.get_base_stations_inside_bounds(
            bounds[0][0], bounds[1][0], bounds[0][1], bounds[1][1])\
            .filter(radio='GSM')
        heatMap = HeatMap(bss, bounds)
        bs_coordinates = list(map(lambda bs: [bs.point.x, bs.point.y], bss))

        context = {'location': location,
                   'base_stations': bs_coordinates,
                   'heatmap': heatMap.generate_heatmap()}
        return render(request, self.template_name, context)

demo/templates/demo/example.html
{% load leaflet_tags %}
<html>
  <head>
    <script type="module">export {Spinner};</script>
    {% leaflet_js %}
    {% leaflet_css %}
      <style>
      .leaflet-container {
        height: 100%;
      }
    </style>
    <script type="text/javascript">
      // Estimated location with GeoIP2
      var baseLocation = {{ location | safe }};
      var baseStations = {{ base_stations }};
      var suggestions = {{ suggestions }};     

      window.addEventListener("map:init", function(event) {
        var map = event.detail.map;
        for(i = 0; i < baseStations.length; i++) {
            L.marker({lon: baseStations[i][0], lat: baseStations[i][1]}).addTo(map);
        }

        var redIcon = new L.Icon({
          iconUrl: 'https://cdn.rawgit.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-red.png',
          shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
          iconSize: [25, 41],
          iconAnchor: [12, 41],
          popupAnchor: [1, -34],
          shadowSize: [41, 41]
        });

        for(i = 0; i < suggestions.length; i++) {
          L.marker({lon: suggestions[i][0], lat: suggestions[i][1]}, {icon: redIcon}).addTo(map);
          {% comment %} L.circle({lon: suggestions[i][0], lat: suggestions[i][1]}, {
                color: 'red',
                fillColor: '#f03',
                fillOpacity: 0.1,
                radius: 500
                }).addTo(map); {% endcomment %}
        }
        map.on('click', function(e){
          var popup = L.popup();
          
          popup
          .setLatLng(e.latlng)
          .setContent("You clicked the map at " + e.latlng.toString())
          .openOn(map);
        });
        map.setView({lon: baseLocation[0], lat: baseLocation[1]}, 17);
      });
    </script>
  </head>
  <body>
    {% leaflet_map 'main' %}
  </body>
</html>

demo/templates/demo/heat-map.html
{% load leaflet_tags %}
<html>
  <head>
    <script type="module">export {Spinner};</script>
    {% leaflet_js %}
    {% leaflet_css %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.heat/0.2.0/leaflet-heat.js"></script>
      <style>
      .leaflet-container {
        height: 100%;
      }
    </style>
    <script type="text/javascript">
      // Estimated location with GeoIP2
      var baseLocation = {{ location | safe }};
      var baseStations = {{ base_stations }};
      var heatmap = {{heatmap}}

   

      window.addEventListener("map:init", function(event) {
        var map = event.detail.map;
        for(i = 0; i < baseStations.length; i++) {
            L.marker({lon: baseStations[i][0], lat: baseStations[i][1]}).addTo(map);
        }      
        map.setView({lon: baseLocation[0], lat: baseLocation[1]}, 17);
        var heat = L.heatLayer(heatmap, {radius: 25, gradient: {0.4: 'blue', 0.65: 'lime', 1: 'red'}}).addTo(map);
        map.on('click', function(e){
          var popup = L.popup();
          
          popup
          .setLatLng(e.latlng)
          .setContent("You clicked the map at " + e.latlng.toString())
          .openOn(map);
        });

      });
    </script>
  </head>
  <body>
    {% leaflet_map 'main' %}
  </body>
</html>

demo/templates/demo/optimization.html
<html>
  <head>
   
  </head>
  <body>
    <ul>
        <li>
            <a href="{% url 'demo:taguchi'  %}?min_lat=-46.74&max_lat=-46.70&min_long=-23.58&max_long=-23.55">
                Taguchi
            </a>
        </li>
        <li>
            <a href="{% url 'demo:slsqp'  %}?min_lat=-46.74&max_lat=-46.70&min_long=-23.58&max_long=-23.55">
                SLSPQ
            </a>
        </li>
        <li>
            <a href="{% url 'demo:basinhopping'  %}?min_lat=-46.74&max_lat=-46.70&min_long=-23.58&max_long=-23.55">
                Basinhopping
            </a>
        </li>
    </ul>    
  </body>
</html>